#include "lexer.h"

const char *token_type_name(TokenType type)
{
  switch (type)
  {
  case TOKEN_IDENTIFIER:
    return "TOKEN_IDENTIFIER";
  case TOKEN_NUMBER:
    return "TOKEN_NUMBER";
  case TOKEN_STRING:
    return "TOKEN_STRING";
  case TOKEN_LET:
    return "TOKEN_LET";
  case TOKEN_FUNC:
    return "TOKEN_FUNC";
  case TOKEN_IF:
    return "TOKEN_IF";
  case TOKEN_ELSE:
    return "TOKEN_ELSE";
  case TOKEN_TRUE:
    return "TOKEN_TRUE";
  case TOKEN_FALSE:
    return "TOKEN_FALSE";
  case TOKEN_EQUAL:
    return "TOKEN_EQUAL";
  case TOKEN_EQUAL_EQUAL:
    return "TOKEN_EQUAL_EQUAL";
  case TOKEN_BANG_EQUAL:
    return "TOKEN_BANG_EQUAL";
  case TOKEN_GREATER_EQUAL:
    return "TOKEN_GREATER_EQUAL";
  case TOKEN_LESS_EQUAL:
    return "TOKEN_LESS_EQUAL";
  case TOKEN_GREATER:
    return "TOKEN_GREATER";
  case TOKEN_LESS:
    return "TOKEN_LESS";
  case TOKEN_LPAREN:
    return "TOKEN_LPAREN";
  case TOKEN_RPAREN:
    return "TOKEN_RPAREN";
  case TOKEN_LBRACE:
    return "TOKEN_LBRACE";
  case TOKEN_RBRACE:
    return "TOKEN_RBRACE";
  case TOKEN_LBRACKET:
    return "TOKEN_LBRACKET";
  case TOKEN_RBRACKET:
    return "TOKEN_RBRACKET";
  case TOKEN_PLUS:
    return "TOKEN_PLUS";
  case TOKEN_MINUS:
    return "TOKEN_MINUS";
  case TOKEN_STAR:
    return "TOKEN_STAR";
  case TOKEN_SLASH:
    return "TOKEN_SLASH";
  case TOKEN_COMMA:
    return "TOKEN_COMMA";
  case TOKEN_SEMICOLON:
    return "TOKEN_SEMICOLON";
  case TOKEN_COLON:
    return "TOKEN_COLON";
  case TOKEN_BANG:
    return "TOKEN_BANG";
  case TOKEN_DOT:
    return "TOKEN_DOT";
  case TOKEN_AND:
    return "TOKEN_AND";
  case TOKEN_OR:
    return "TOKEN_OR";
  case TOKEN_ARROW:
    return "TOKEN_ARROW";
  case TOKEN_QUESTION:
    return "TOKEN_QUESTION";
  case TOKEN_REFLECT:
    return "TOKEN_REFLECT";
  case TOKEN_EOF:
    return "TOKEN_EOF";
  case TOKEN_ERROR:
    return "TOKEN_ERROR";
  case TOKEN_UNDERSCORE:
    return "TOKEN_UNDERSCORE";
  case TOKEN_MATCH:
    return "TOKEN_MATCH";
  case TOKEN_FN:
    return "TOKEN_FN";
  case TOKEN_DOLLAR:
    return "TOKEN_DOLLAR";
  case TOKEN_ASYNC:
    return "TOKEN_ASYNC";
  case TOKEN_AWAIT:
    return "TOKEN_AWAIT";
  case TOKEN_THROW:
    return "TOKEN_THROW";
  case TOKEN_TRY:
    return "TOKEN_TRY";
  case TOKEN_CATCH:
    return "TOKEN_CATCH";
  case TOKEN_IMPORT:
    return "TOKEN_IMPORT";
  case TOKEN_PIPE:
    return "TOKEN_PIPE";
  case TOKEN_PIPELINE:
    return "TOKEN_PIPELINE";
  case TOKEN_LARROW:
    return "TOKEN_LARROW";
  default:
    return "TOKEN_UNKNOWN";
  }
}
